api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "bundler"
uid = "a5351d30-e2eb-5068-e530-bbe4d13698bd1d290638"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
