api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "capped-discount"
uid = "27499398-0c38-2bb1-2165-803069b6fcc9c8c55aeb"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"

[extensions.input.variables]
namespace = "discount_code"
key = "function_configuration"

  [extensions.input.variables.fields]
  eligibleCollectionIds = "list_of_strings"
  percentage_discount = "string"
  maximum_discount_amount = "string"