api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "combo-builder"
uid = "424d0ac3-259e-d7b0-daab-fcac4847e339ba1caa36"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/combo-builder/app"
  details = "/combo-builder/:functionId/:id"


