api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "dynamic-combo"
uid = "ae2dfd6a-86af-7b28-7e34-3328e055a840256bf1dd"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
