api_version = "2024-01"

[[extensions]]
handle = "product-discount-js"
name = "t:name"
description = "t:description"
type = "function"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/product-discount/app"
  details = "/product-discount/:functionId/:id"
  
  [extensions.input.variables]
  namespace = "product-discount"
  key = "function-configuration"

