api_version = "2026-01"

[[extensions]]
handle = "product-discount-js"
uid = "fa81b4ed-bcec-5f88-a70b-86526fcc8d6c876cc78a"
name = "t:name"
description = "t:description"
type = "function"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/product-discount/app"
  details = "/product-discount/:functionId/:id"
  
  [extensions.input.variables]
  namespace = "product-discount"
  key = "function-configuration"

