api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "tiered-coupon"
uid = "eaf9de36-81c8-5409-b414-5090743f6b9e5c79d965"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
