api_version = "unstable"

[[extensions]]
name = "t:name"
handle = "coupon-value-limit"
uid = "9152b29f-02f7-c1e7-9cd6-1d7c213ce79fb771e37a"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.discounts-allocator.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
